Repository mitre/heimdall2, pull requests merged in 2020-09, with the labels that each got.

#130 Change single-expand and mutliple-expand to be reactive
  apps/frontend/src/components/cards/controltable/ControlTable.vue
Labels: enhancement

#132 Monorepo cleanup
  .github/workflows/e2e-backend-tests.yml
  .github/workflows/frontend-tests.yml
  README.md
  apps/backend/package.json
  apps/backend/src/evaluation-tags/dto/create-evaluation-tag.dto.ts
  apps/backend/src/evaluation-tags/dto/evaluation-tag.dto.ts
  apps/backend/src/evaluation-tags/dto/update-evaluation-tag.dto.ts
  apps/backend/src/evaluations/dto/create-evaluation.dto.ts
  apps/backend/src/evaluations/dto/evaluation.dto.ts
  apps/backend/src/evaluations/dto/update-evaluation.dto.ts
  apps/backend/src/users/dto/create-user.dto.ts
  apps/backend/src/users/dto/delete-user.dto.ts
  apps/backend/src/users/dto/update-user.dto.ts
  apps/backend/src/users/dto/user.dto.ts
  apps/backend/tsconfig.app.json
  apps/backend/tsconfig.build.json
  apps/backend/tsconfig.json
  apps/frontend/package.json
  apps/frontend/src/main.ts
  apps/frontend/tsconfig.json
  heimdall2.code-workspace
  lerna.json
  libs/interfaces/.eslintrc.js
  libs/interfaces/evaluation-tag/create-evaluation-tag.interface.ts
  libs/interfaces/evaluation-tag/evaluation-tag.interface.ts
  libs/interfaces/evaluation-tag/update-evaluation-tag.interface.ts
  libs/interfaces/evaluation/create-evaluation.interface.ts
  libs/interfaces/evaluation/evaluation.interface.ts
  libs/interfaces/evaluation/update-evaluation.interface.ts
  libs/interfaces/index.ts
  libs/interfaces/package.json
  libs/interfaces/tsconfig.json
  libs/interfaces/user/create-user.interface.ts
  libs/interfaces/user/delete-user.interface.ts
  libs/interfaces/user/update-user.interface.ts
  libs/interfaces/user/user.interface.ts
  package-lock.json
  package.json
  tsconfig.json
Labels: enhancement

#122 Evaluation Tags (CUD) via Evaluation API
  apps/backend/src/database/database.service.spec.ts
  apps/backend/src/database/database.service.ts
  apps/backend/src/database/interfaces/delta-args.interface.ts
  apps/backend/src/evaluation-tags/dto/create-evaluation-tag.dto.ts
  apps/backend/src/evaluation-tags/dto/delete-evaluation-tag.dto.ts
  apps/backend/src/evaluation-tags/dto/update-evaluation-tag.dto.ts
  apps/backend/src/evaluation-tags/evaluation-tags.service.ts
  apps/backend/src/evaluations/dto/update-evaluation.dto.ts
  apps/backend/src/evaluations/evaluations.service.spec.ts
  apps/backend/src/evaluations/evaluations.service.ts
  apps/backend/test/constants/evaluation-tags-test.constant.ts
  apps/backend/test/constants/evaluations-test.constant.ts
  libs/interfaces/evaluation-tag/delete-evaluation-tag.interface.ts
  libs/interfaces/evaluation/update-evaluation.interface.ts
  libs/interfaces/index.ts
Labels: backend, enhancement

#138 Update README
  README.md
Labels: chore, documentation

#127 Adding Dockerbuild and deploy code
  .gitignore
  Dockerfile
  README.md
  apps/backend/seeders/20200514154327-create-administrator.js
  apps/backend/seeders/20200520192456-create-policy-admin-delete-users.js
  apps/backend/seeders/20200629190950-create-policy-users-delete-users.js
  apps/backend/seeders/20200630161936-create-policy-user-update-users.js
  cmd.sh
  docker-compose.yml
  setup-docker-secrets.sh
Labels: distribution, enhancement, packaging
