Repository mitre/heimdall2, pull requests merged in 2021-12, with the labels that each got.

#2243 [WIP] Restore Splunk Data Store and Testing
  .github/workflows/e2e-ui-tests.yml
  apps/backend/test/constants/users-test.constant.ts
  apps/frontend/src/components/global/UploadNexus.vue
  apps/frontend/src/components/global/upload_tabs/splunk/AuthStep.vue
  apps/frontend/src/components/global/upload_tabs/splunk/FileList.vue
  apps/frontend/src/components/global/upload_tabs/splunk/SplunkReader.vue
  apps/frontend/src/utilities/splunk_util.ts
  test/configs/splunk/server.conf
  test/integration/splunk.spec.ts
  test/support/pages/SplunkPage.ts
  test/support/verifiers/SplunkTabVerifier.ts
  test/support/verifiers/ToastVerifier.ts
Labels: ready-to-merge

#2262 Trim ASFF Input before processing
  libs/hdf-converters/src/asff-mapper.ts
Labels: ready-to-merge

#2263 Fix Exporting Overlays as CSV
  apps/frontend/src/components/global/ExportCSVModal.vue
Labels: ready-to-merge

#2266 Fix EvaluationTagRow
  apps/frontend/src/components/global/tags/TagRow.vue
Labels: enhancement, ready-to-merge

#2265 Ensure Caveat is Displayed First in CSV Descriptions (if available)
  apps/frontend/src/components/global/ExportCSVModal.vue
Labels: bug, enhancement, ready-to-merge

#1798 Add SonarQube mapper
  .github/workflows/e2e-ui-tests.yml
  .github/workflows/hdfconverter-tests.yml
  libs/hdf-converters/index.ts
  libs/hdf-converters/package.json
  libs/hdf-converters/sample_jsons/sonarqube_mapper/sonarqube-hdf.json
  libs/hdf-converters/src/sonarqube-mapper.ts
  libs/hdf-converters/test/hdf_checker.spec.ts
  test/package.json
  test/support/server/SonarQube.json
  test/support/server/json-server.js
Labels: enhancement, ready-to-merge

#2279 Clarify Admin Password Change Message
  apps/backend/seeders/20200514154327-create-administrator.js
Labels: bug, ready-to-merge

#1794 Aws config mapper
  libs/hdf-converters/package.json
  libs/hdf-converters/src/aws-config-mapper.ts
  libs/hdf-converters/test/hdf_checker.spec.ts
  yarn.lock
Labels: enhancement
