Repository mitre/heimdall2, pull requests merged in 2022-03, with the labels that each got.

#2735 Support Multi-file Return Filenames in Heimdall
  apps/frontend/src/store/report_intake.ts
Labels: ready-to-merge

#2738 Export NIST Tags in CSV when CCIs are not Defined
  apps/frontend/src/components/global/ExportCSVModal.vue
Labels: ready-to-merge

#2731 Remove 'unmapped' NIST Tag from AWS Config Mapper and Fortify Mapper
  libs/hdf-converters/src/aws-config-mapper.ts
  libs/hdf-converters/src/fortify-mapper.ts
Labels: ready-to-merge

#2736 Add All Tags to Details Tab
  apps/frontend/src/components/cards/controltable/ControlRowDetails.vue
Labels: ready-to-merge

#2730 Support JSON Syntax Highlighting on Code Tab
  apps/frontend/src/components/cards/controltable/ControlRowDetails.vue
Labels: heimdall-frontend, ready-to-merge

#2728 Add project key to Sonarqube Mapper Output
  libs/hdf-converters/sample_jsons/sonarqube_mapper/sonarqube-hdf.json
  libs/hdf-converters/src/sonarqube-mapper.ts
Labels: ready-to-merge

#2734 Optimize Dockerfile
  Dockerfile
Labels: ready-to-merge

#2737 Update NIST 800-53 Lookup URL
  apps/frontend/src/components/cards/controltable/ControlRowHeader.vue
Labels: ready-to-merge

#2675 Splunk2HDF Updates
  apps/frontend/package.json
  apps/frontend/public/index.html
  apps/frontend/src/components/global/ExportSplunkModal.vue
  apps/frontend/src/components/global/upload_tabs/splunk/AuthStep.vue
  apps/frontend/src/components/global/upload_tabs/splunk/FileList.vue
  apps/frontend/src/components/global/upload_tabs/splunk/SplunkReader.vue
  apps/frontend/src/types/splunk-sdk/index.d.ts
  apps/frontend/src/utilities/helper_util.ts
  apps/frontend/src/utilities/splunk_util.ts
  apps/frontend/src/views/Results.vue
  libs/hdf-converters/index.ts
  libs/hdf-converters/src/converters-from-hdf/splunk/Schemas.md
  libs/hdf-converters/src/converters-from-hdf/splunk/reverse-splunk-mapper.ts
  libs/hdf-converters/src/splunk-mapper.ts
  libs/hdf-converters/test/mappers/reverse/splunk_reverse_mapper.spec.ts
  libs/hdf-converters/types/splunk-sdk/index.d.ts
  tsconfig.json
  types/splunk-sdk-no-env/index.d.ts
Labels: bug, enhancement, ready-to-merge

#2777 Update hdf2splunk Schema README
  libs/hdf-converters/src/converters-from-hdf/splunk/Schemas.md
Labels: ready-to-merge
