Repository mitre/heimdall2, pull requests merged in 2023-08, with the labels that each got.

#3922 Implemented OIDC external group import
  apps/backend/.env-example
  apps/backend/src/authn/authn.module.ts
  apps/backend/src/authn/oidc.strategy.ts
  apps/backend/src/groups/groups.service.ts
Labels: ready-to-merge

#4767 Using Semver Compare for ASFF "Previously HDF" Special Casing
  libs/hdf-converters/package.json
  libs/hdf-converters/src/asff-mapper/asff-mapper.ts
  yarn.lock
Labels: ready-to-merge

#4722 Unique Group Names
  apps/backend/migrations/20230725092535-change-group-names-to-unique.js
  apps/backend/src/groups/groups.service.ts
  apps/frontend/src/components/global/groups/GroupModal.vue
  test/integration/groups.cy.ts
  test/support/pages/GroupPage.ts
Labels: ready-to-merge

#4792 Avoid Hard Refresh When Saving Group
  apps/frontend/src/components/global/RegistrationModal.vue
  apps/frontend/src/components/global/groups/GroupModal.vue
  apps/frontend/src/store/server.ts
Labels: ready-to-merge

#4818 Truncate compliance percentage in the comparison view
  apps/frontend/src/components/cards/StatusChart.vue
Labels: ready-to-merge

#4586 Refactor Export HTML Feature
  .gitignore
  apps/frontend/.gitignore
  apps/frontend/package.json
  apps/frontend/public/static/export/template.html
  apps/frontend/src/components/cards/ComplianceChart.vue
  apps/frontend/src/components/cards/StatusChart.vue
  apps/frontend/src/components/global/ExportHTMLModal.vue
  apps/frontend/src/components/global/PrintButton.vue
  apps/frontend/src/tailwind.css
  apps/frontend/src/utilities/compliance_util.ts
  apps/frontend/src/views/Results.vue
  apps/frontend/tailwind.config.js
  apps/frontend/vue.config.js
  yarn.lock
Labels: enhancement, heimdall-frontend, ready-to-merge, javascript

#4834 Move HTML export feature to HDF Converters
  apps/frontend/.gitignore
  apps/frontend/package.json
  apps/frontend/src/components/cards/ComplianceChart.vue
  apps/frontend/src/components/cards/StatusChart.vue
  apps/frontend/src/components/global/ExportHTMLModal.vue
  apps/frontend/tailwind.config.js
  apps/frontend/vue.config.js
  libs/hdf-converters/index.ts
  libs/hdf-converters/package.json
  libs/hdf-converters/src/converters-from-hdf/html/html-types.ts
  libs/hdf-converters/src/converters-from-hdf/html/reverse-html-mapper.ts
  libs/hdf-converters/src/converters-from-hdf/html/template.html
  libs/hdf-converters/src/utils/compliance.ts
Labels: enhancement, heimdall-frontend, ready-to-merge, hdf-converters, javascript
