Repository mitre/heimdall2, pull requests merged in 2023-07, with the labels that each got.

#4674 checklistView fix search sync
  apps/frontend/src/mixins/RouteMixin.ts
Labels: ready-to-merge

#4659 Admin panel
  apps/backend/src/groups/groups.controller.spec.ts
  apps/backend/src/groups/groups.controller.ts
  apps/frontend/src/components/global/TopbarDropdown.vue
  apps/frontend/src/components/global/groups/GroupManagement.vue
  apps/frontend/src/components/global/groups/GroupModal.vue
  apps/frontend/src/components/global/groups/GroupUsers.vue
  apps/frontend/src/components/global/groups/Users.vue
  apps/frontend/src/views/Admin.vue
  apps/frontend/src/views/Groups.vue
Labels: ready-to-merge

#4632 Improving Splunk Interface
  apps/frontend/src/components/global/ExportSplunkModal.vue
  apps/frontend/src/components/global/upload_tabs/aws/AuthStepBasic.vue
  apps/frontend/src/components/global/upload_tabs/aws/AuthStepMFA.vue
  apps/frontend/src/components/global/upload_tabs/aws/S3Reader.vue
  apps/frontend/src/components/global/upload_tabs/splunk/AuthStep.vue
  apps/frontend/src/components/global/upload_tabs/splunk/FileList.vue
  apps/frontend/src/components/global/upload_tabs/splunk/SplunkReader.vue
  apps/frontend/src/components/global/upload_tabs/tenable/AuthStep.vue
  apps/frontend/src/components/global/upload_tabs/tenable/FileList.vue
  apps/frontend/src/utilities/upload_util.ts
  libs/hdf-converters/src/splunk-mapper.ts
Labels: bug, enhancement, heimdall-frontend, ready-to-merge

#4716 Update Splunk links
  apps/frontend/src/components/global/ExportSplunkModal.vue
  apps/frontend/src/components/global/upload_tabs/splunk/SplunkReader.vue
Labels: bug, ready-to-merge

#4403 Reassign group owners upon user deletion
  apps/backend/config/app_config.ts
  apps/backend/src/apikeys/apikeys.module.ts
  apps/backend/src/evaluation-tags/evaluation-tags.service.spec.ts
  apps/backend/src/groups/groups.controller.ts
  apps/backend/src/groups/groups.module.ts
  apps/backend/src/groups/groups.service.spec.ts
  apps/backend/src/groups/groups.service.ts
  apps/backend/src/users/users.controller.spec.ts
  apps/backend/src/users/users.module.ts
  apps/backend/src/users/users.service.spec.ts
  apps/backend/src/users/users.service.ts
  apps/backend/test/constants/groups-test.constant.ts
  apps/backend/test/constants/users-test.constant.ts
  apps/frontend/src/components/generic/ActionDialog.vue
  apps/frontend/src/components/global/admin/UserManagement.vue
  apps/frontend/src/components/global/groups/GroupModal.vue
  apps/frontend/src/components/global/groups/Users.vue
Labels: ready-to-merge

#4695 Group Descriptions
  apps/backend/migrations/20230712110759-add_desc_to_groups.js
  apps/backend/src/groups/dto/create-group.dto.ts
  apps/backend/src/groups/dto/group.dto.ts
  apps/backend/src/groups/group.model.ts
  apps/backend/src/groups/groups.controller.spec.ts
  apps/backend/test/constants/groups-test.constant.ts
  apps/frontend/src/components/global/groups/GroupManagement.vue
  apps/frontend/src/components/global/groups/GroupModal.vue
  libs/interfaces/group/create-group.interface.ts
  libs/interfaces/group/group.interface.ts
Labels: ready-to-merge

#4602 Update Netsparker mapper
  libs/hdf-converters/sample_jsons/netsparker_mapper/netsparker-hdf-withraw.json
  libs/hdf-converters/sample_jsons/netsparker_mapper/netsparker-hdf.json
  libs/hdf-converters/sample_jsons/netsparker_mapper/sample_input_report/sample-netsparker-invicti.xml
  libs/hdf-converters/src/netsparker-mapper.ts
  libs/hdf-converters/test/mappers/forward/netsparker_mapper.spec.ts
Labels: enhancement, ready-to-merge, hdf-converters

#4735 Add `None` category to severity summary chart
  apps/frontend/src/components/cards/SeverityChart.vue
  apps/frontend/src/plugins/vuetify.ts
Labels: enhancement, ready-to-merge

#4752 Remove jQuery import
  apps/frontend/public/index.html
Labels: heimdall-frontend, ready-to-merge, javascript
