Repository mitre/heimdall2, pull requests merged in 2024-07, with the labels that each got.

#5902 checklist metadata input validation on export
  apps/frontend/src/components/global/ExportCKLModal.vue
  libs/hdf-converters/index.ts
  libs/hdf-converters/package.json
  libs/hdf-converters/sample_jsons/checklist_mapper/sample_input_report/invalid_metadata.ckl
  libs/hdf-converters/sample_jsons/checklist_mapper/sample_input_report/invalid_metadata.json
  libs/hdf-converters/src/ckl-mapper/checklist-jsonix-converter.ts
  libs/hdf-converters/src/ckl-mapper/checklist-mapper.ts
  libs/hdf-converters/src/ckl-mapper/checklist-metadata-utils.ts
  libs/hdf-converters/src/utils/result.ts
  libs/hdf-converters/test/mappers/forward/checklist_mapper.spec.ts
  libs/hdf-converters/test/mappers/reverse/checklist_reverse_mapper.spec.ts
  yarn.lock
Labels: ready-to-merge

#6023 Format error message when validating checklist metadata
  libs/hdf-converters/src/ckl-mapper/checklist-metadata-utils.ts
Labels: enhancement, ready-to-merge

#6013 Trufflehog mapper
  apps/frontend/src/components/global/upload_tabs/FileReader.vue
  apps/frontend/src/store/report_intake.ts
  libs/hdf-converters/README.md
  libs/hdf-converters/index.ts
  libs/hdf-converters/sample_jsons/trufflehog_mapper/sample_input_report/trufflehog-report-example.json
  libs/hdf-converters/sample_jsons/trufflehog_mapper/sample_input_report/trufflehog.json
  libs/hdf-converters/sample_jsons/trufflehog_mapper/sample_input_report/trufflehog_docker_example.json
  libs/hdf-converters/sample_jsons/trufflehog_mapper/sample_input_report/trufflehog_saf_example.json
  libs/hdf-converters/sample_jsons/trufflehog_mapper/trufflehog-docker-hdf-withraw.json
  libs/hdf-converters/sample_jsons/trufflehog_mapper/trufflehog-docker-hdf.json
  libs/hdf-converters/sample_jsons/trufflehog_mapper/trufflehog-hdf-withraw.json
  libs/hdf-converters/sample_jsons/trufflehog_mapper/trufflehog-hdf.json
  libs/hdf-converters/sample_jsons/trufflehog_mapper/trufflehog-report-example-hdf-withraw.json
  libs/hdf-converters/sample_jsons/trufflehog_mapper/trufflehog-report-example-hdf.json
  libs/hdf-converters/sample_jsons/trufflehog_mapper/trufflehog-saf-hdf-withraw.json
  libs/hdf-converters/sample_jsons/trufflehog_mapper/trufflehog-saf-hdf.json
  libs/hdf-converters/src/trufflehog-mapper.ts
  libs/hdf-converters/src/utils/fingerprinting.ts
  libs/hdf-converters/test/mappers/forward/trufflehog_mapper.spec.ts
Labels: enhancement, ready-to-merge, hdf-converters

#5982 gosec Mapper Rework
  apps/frontend/src/components/cards/controltable/ControlRowCol.vue
  apps/frontend/src/components/global/upload_tabs/FileReader.vue
  apps/frontend/src/store/report_intake.ts
  libs/hdf-converters/README.md
  libs/hdf-converters/sample_jsons/gosec_mapper/go-ethereum-all-unsuppressed-gosec-hdf-withraw.json
  libs/hdf-converters/sample_jsons/gosec_mapper/go-ethereum-all-unsuppressed-gosec-hdf.json
  libs/hdf-converters/sample_jsons/gosec_mapper/go-ethereum-external-unsuppressed-gosec-hdf-withraw.json
  libs/hdf-converters/sample_jsons/gosec_mapper/go-ethereum-external-unsuppressed-gosec-hdf.json
  libs/hdf-converters/sample_jsons/gosec_mapper/gosec-hdf.json
  libs/hdf-converters/sample_jsons/gosec_mapper/grype-gosec-hdf-withraw.json
  libs/hdf-converters/sample_jsons/gosec_mapper/grype-gosec-hdf.json
  libs/hdf-converters/sample_jsons/gosec_mapper/sample_input_report/Go_Ethereum_gosec_results_all_suppressed.json
  libs/hdf-converters/sample_jsons/gosec_mapper/sample_input_report/Go_Ethereum_gosec_results_external_suppressed.json
  libs/hdf-converters/src/gosec-mapper.ts
  libs/hdf-converters/test/mappers/forward/gosec_mapper.spec.ts
Labels: bug, enhancement, ready-to-merge
