Repository mitre/heimdall2, pull requests merged in 2024-08, with the labels that each got.

#6007 Convert Microsoft Secure Score to OHDF
  apps/frontend/src/components/global/upload_tabs/FileReader.vue
  apps/frontend/src/store/report_intake.ts
  libs/hdf-converters/README.md
  libs/hdf-converters/index.ts
  libs/hdf-converters/package.json
  libs/hdf-converters/sample_jsons/msft_secure_score_mapper/sample_input_report/combined.json
  libs/hdf-converters/sample_jsons/msft_secure_score_mapper/sample_input_report/profiles.json
  libs/hdf-converters/sample_jsons/msft_secure_score_mapper/sample_input_report/secureScore-multiple.json
  libs/hdf-converters/sample_jsons/msft_secure_score_mapper/sample_input_report/secureScore.json
  libs/hdf-converters/sample_jsons/msft_secure_score_mapper/secure_score-hdf-multi.json
  libs/hdf-converters/sample_jsons/msft_secure_score_mapper/secure_score-hdf-withraws.json
  libs/hdf-converters/sample_jsons/msft_secure_score_mapper/secure_score-hdfs.json
  libs/hdf-converters/src/msft-secure-score-mapper.ts
  libs/hdf-converters/src/utils/fingerprinting.ts
  libs/hdf-converters/test/mappers/forward/msft_secure_score_mapper.spec.ts
  yarn.lock
Labels: enhancement, ready-to-merge, hdf-converters

#6054 Twistlock Mapper Tweaks
  libs/hdf-converters/src/twistlock-mapper.ts
Labels: bug, ready-to-merge

#6112 Remove passport openid
  apps/backend/package.json
  apps/backend/src/types/passport-openid/index.d.ts
  yarn.lock
Labels: ready-to-merge
