Repository mitre/heimdall2, pull requests merged in 2024-02, with the labels that each got.

#5410 Add ability to inject cacerts into the Heimdall container
  .github/workflows/hdfconverter-tests.yml
  .gitignore
  README.md
  certs/dodcerts.sh
  certs/mitrecerts.sh
  docker-compose.yml
  libs/hdf-converters/src/utils/splunk-tools.ts
  libs/hdf-converters/test/mappers/reverse/splunk_reverse_mapper.spec.ts
  setup-docker-env.sh
Labels: enhancement

#5414 Db schema scripts
  apps/backend/db/heimdall_database_script.sql
Labels: enhancement

#5512 Alternate passport-openidconnect 1.1.0
  .gitignore
  apps/backend/package.json
  apps/backend/src/authn/oidc.strategy.ts
  yarn.lock
Labels: ready-to-merge

#5555 groupUsersBugFix
  apps/backend/src/evaluations/evaluations.controller.ts
  apps/backend/src/evaluations/evaluations.service.ts
  apps/frontend/src/components/global/upload_tabs/DatabaseReader.vue
  apps/frontend/src/components/global/upload_tabs/SampleList.vue
Labels: bug

#5574 Node1819plus
  .github/workflows/auto-approve-and-merge.yml
  .github/workflows/backend-tests.yml
  .github/workflows/build-prod.yml
  .github/workflows/draft-release.yml
  .github/workflows/e2e-ui-tests.yml
  .github/workflows/frontend-tests.yml
  .github/workflows/gh-pages.yml
  .github/workflows/hdfconverter-tests.yml
  .github/workflows/inspecjs-tests.yml
  .github/workflows/linter.yml
  .github/workflows/push-lite-to-docker.yml
  .github/workflows/push-server-to-docker.yml
  .github/workflows/push-to-npm.yml
  .github/workflows/release-lite-to-docker.yml
  .github/workflows/release-server-to-docker.yml
  .nvmrc
  Dockerfile
  Dockerfile.lite
  apps/backend/package.json
  apps/frontend/package.json
  libs/hdf-converters/package.json
  package.json
  yarn.lock
Labels: ready-to-merge
